FROM postgres:latest

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    make \
    python3\
    python3-pip \
    python3-venv \
    postgresql-server-dev-all \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/pgvector/pgvector.git \
    && cd pgvector \
    && make \
    && make install